repository_type: pipeline
lint:
  files_unchanged:
    - assets/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_light.png
    - docs/images/nf-core-epitopeprediction_logo_dark.png
nf_core_version: "2.14.1"
